### ISSUE TITLE
Починить ошибку "TelegramForbiddenError"

### ISSUE THREAD

**Issue by romka-best** [romka-best/gpts-turbo-bot#2]
Суть ошибки в том, что мы пытаемся отправить сообщение пользователю, который заблокировал нашего бота. В БД в таблицу "User" надо добавить поле "is_banned", которое будет отвечать заблокировал ли пользователь нашего бота или нет

**Comment by Mark-TinZ** [comment]
В API Telegram нет возможности узнать заблокировал ли бользователь бота. Вы можете отслеживать ответ, если возникает исключение вы можете его сохранять в ячейку is_banned.

**Comment by Garpusha** [comment]
> В API Telegram нет возможности узнать заблокировал ли бользователь бота. Вы можете отслеживать ответ, если возникает исключение вы можете его сохранять в ячейку is_banned.

@admin_router.my_chat_member(ChatMemberUpdatedFilter(member_status_changed=IS_NOT_MEMBER))
async def user_blocked_bot(event: ChatMemberUpdated):
    chat_id = str(event.from_user.id)
    blocked_status_update(chat_id, True)
